NAME            = 'zip'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira_1@users.sourceforge.net'
VERSION         = '0.1'
MODULE_DEPS     = 'io'

set_options = configure = distclean = lambda p: None

def build(bld):
    variant = bld.env['VARIANT'] or 'default'
    env = bld.env_of_name(variant)
    
    kw = globals().copy()
    if 'MAKE_ZIP' in env:
        kw['USELIB_LOCAL'] = 'ZIP'
    else:
        kw['USELIB'] = 'ZIP'
    bld.module(**kw)
