NAME            = 'numpyutils'
MAINTAINER      = 'anuraag.pakanati@mdaus.com'
VERSION         = '1.0'
MODULE_DEPS     = 'numpy types-c++ except-c++'
USELIB          = 'numpy'

import os, sys
from os.path import join, exists
from waflib import Options
from waflib.TaskGen import feature, before, task_gen

distclean = options = configure = lambda x: None

def configure(conf):    
    if Options.options.enable_numpy:
       nputilsinclude = os.path.join(conf.path.abspath(), 'include')
       conf.check(
                  uselib_store='numpyutils',
                  includes=nputilsinclude,
                  msg='Checking for numpyutils',
                  mandatory=True) 
            

       conf.undefine("HAVE_NUMPYUTILS_NUMPYUTILS_H")

def build(bld):
    bld.module(**globals())
