import os
from waflib import Scripting, Options
from os.path import join, exists 

VERSION = '2.0-dev'
APPNAME = 'CODA'
top  = '.'
out  = 'target'

DIRS = 'drivers c++'

def options(opt):
    opt.load('build matlabtool', tooldir='./build/')
    # always set_options on all
    opt.recurse(filter(lambda x: exists(join(opt.path.abspath(), x, 'wscript')),
                           DIRS.split()))

def configure(conf):
    conf.load('build matlabtool', tooldir='./build/')
    conf.recurse(filter(lambda x: exists(join(conf.path.abspath(), x, 'wscript')),
                           DIRS.split()))

def build(bld):
    bld.recurse(filter(lambda x: exists(join(bld.path.abspath(), x, 'wscript')),
                           DIRS.split()))
        
def distclean(context):
    context.recurse(filter(lambda x: exists(join(context.path.abspath(), x, 'wscript')),
                           DIRS.split()))    
    Scripting.distclean(context)
