#!/usr/bin/env python

# If you are reading this, I assume you've made an update to waf and are trying to figure out
# how to repackage it.

# First, create a new directory containing the updated `waflib` folder.
# Copy the contents of the following waf build files for the current version (1.7.14):
#  - https://gitlab.com/ita1024/waf/raw/waf-1.7.14/waf-light
#  - https://gitlab.com/ita1024/waf/raw/waf-1.7.14/wscript
#
# Your directory structure should look like this:
# -root
#  |- waflib
#     |- ansiterm.py
#     |- Build.py  #etc
#  |- waf-light
#  |- wscript

# Call `python waf-light configure build`
# Copy the new `waf` file to `coda-oss/build`

import os, sys, subprocess

path_to_waf = os.path.join(os.path.dirname(__file__), 'build', 'waf')

cmd = [sys.executable, path_to_waf] + sys.argv[1:]
try:
    sys.exit(subprocess.call(cmd))
except KeyboardInterrupt:
    sys.exit(1)
