NAME            = 'net'
MAINTAINER      = 'jmrandol@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'logging re mt io mem'
USELIB          = 'NSL SOCKET'
USE             = 'CURL'
TEST_FILTER     = 'AckMulticastSender.cpp ' \
                  'AckMulticastSubscriber.cpp ' \
                  'MulticastSender.cpp ' \
                  'MulticastSubscriber.cpp ' \
                  'SerializableTestClient.cpp'

options = distclean = lambda p: None

def configure(conf):
    conf.env['LIB_CURL'] = 'curl'

def build(bld):
    bld.module(**globals())
