import re

NAME            = 'net'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira1@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 're io'
USELIB          = 'NSL SOCKET'
TEST_FILTER     = lambda x: not re.match(r'.*(Serializable|Multicast).*', x)

set_options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
