import os

options = distclean = lambda p: None

def configure(conf):
    conf.env.append_value('CPPPATH_MATH_LINEAR', os.path.join(conf.path.abspath(), 'include'))
    # legacy
    conf.env.append_value('CPPPATH_math.linear', os.path.join(conf.path.abspath(), 'include'))

def build(bld):
    bld.fromConfig(bld.path)
