NAME            = 'math.linear'
MAINTAINER      = 'jmrandol@users.sourceforge.net'
VERSION         = '0.2'
MODULE_DEPS     = 'sys mem types'

options = configure = distclean = lambda p: None

def build(bld):
    globs = globals()
    if 'HAVE_BOOST' not in bld.env or bld.env['HAVE_BOOST'] is False :
        globs['UNITTEST_FILTER'] = 'test_Matrix2D_serialize.cpp ' + \
                                   'test_Vector_serialize.cpp'
    else :
        globs['UNITTEST_DEPS'] = 'serialize'
        globs['UNITTEST_USELIB'] = 'BOOST_SERIALIZATION'
    bld.module(**globs)