NAME            = 'xml.lite'
MAINTAINER      = 'jmrandol@users.sourceforge.net'
VERSION         = '1.2'
MODULE_DEPS     = 'io mt'
USELIB_CHECK    = 'XML'
TEST_FILTER     = 'MMParserTest1.cpp MinidomParserTest2.cpp'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
