from build import writeConfig
NAME            = 'math'
MAINTAINER      = 'asylvest@users.sourceforge.net'
VERSION         = '0.1'
USELIB          = 'MATH'
MODULE_DEPS     = 'sys'

options = distclean = lambda p: None


def configure(conf):
    def sys_callback(conf):
        conf.check_cc(function_name='isnan', header_name='math.h',
                mandatory=False)

    writeConfig(conf, sys_callback, NAME)

def build(bld):
    bld.module(**globals())
