NAME            = 'math'
MAINTAINER      = 'asylvest@users.sourceforge.net'
VERSION         = '0.1'
USELIB          = 'MATH'
MODULE_DEPS     = 'except str sys types'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
