NAME            = 'str'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira1@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'except'

set_options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
