NAME            = 'numpyutils'
MAINTAINER      = 'anuraag.pakanati@mdaus.com'
VERSION         = '1.0'
MODULE_DEPS     = 'types except sys'
USELIB          = 'NUMPY PYEXT'

from waflib import Options

distclean = options = lambda x: None

def configure(conf):
    conf.recurse(['examples'])

def build(bld):
    if bld.env['PY_HAVE_NUMPY'] and Options.options.enable_numpy:
       bld.module(**globals())
       bld.recurse(['examples'])
