NAME            = 'numpyutils'
MAINTAINER      = 'anuraag.pakanati@mdaus.com'
VERSION         = '1.0'
MODULE_DEPS     = 'numpy types-c++ except-c++'
USELIB          = 'numpy'

import os, sys
from os.path import join, exists
from waflib import Options
from waflib.TaskGen import feature, before, task_gen

distclean = options = configure = lambda x: None

def build(bld):
    if bld.env['PY_HAVE_NUMPY'] and Options.options.enable_numpy:
       bld.module(**globals())
