import os, sys
from os.path import join, exists
from waflib import Options
from waflib.TaskGen import feature, before, task_gen
from build import untarFile


def options(opt):
    opt.add_option('--disable-numpy', action='store_false', dest='enable_numpy', default=True,
                   help='turn off Numpy C headers/libs')
        

def configure(cfg):    
    if Options.options.enable_numpy:
        
        # a little magic borrowed from python-config and extended for numpy and -L flags
        try:
            from distutils import sysconfig
            import numpy.distutils
            import os
            
            np_info = numpy.distutils.misc_util.get_info('npymath')

            warningmessage = ""
            if(len(np_info['include_dirs']) > 1):
                warningmessage += " More than one include directory reported by Numpy.  Using first."
            if(len(np_info['library_dirs']) > 1):
                warningmessage += " More than one lib directory reported by Numpy.  Using first."

            inc_dir = np_info['include_dirs'][0]
            lib_dir = np_info['library_dirs'][0]

            cfg.check(
                        uselib_store='NUMPY',
                        lib='npymath',  
                        header_name='numpy/numpyconfig.h', 
                        includes=inc_dir,
                        libpath=lib_dir,
                        msg='Checking for library numpy' + warningmessage, 
                        mandatory=False) 

            cfg.env['PY_IMPORT_NUMPY'] = True
        except:
            cfg.env['PY_IMPORT_NUMPY'] = False
            cfg.check(
                        lib='npymath',
                        header_name='numpy/numpyconfig.h',
                        msg='Checking for library numpy FAILED'
                     ) 



def build(bld):
    1

def distclean(ctxt):
    1 
