NAME            = 're'
MAINTAINER      = 'adam.sylvester@mdaus.com matthew.wysocki@mdaus.com'
VERSION         = '1.0'
MODULE_DEPS     = 'sys'
USELIB_CHECK    = 'PCRE'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
