NAME            = 're'
MAINTAINER      = 'adam.sylvester@mdaus.com matthew.wysocki@mdaus.com'
VERSION         = '1.0'
MODULE_DEPS     = 'sys'

distclean = lambda p: None

from waflib import Options
from build import writeConfig

def options(opt):
    # We don't make this the default since unfortunately the STL implementation
    # is significantly slower than PCRE
    opt.add_option('--enable-std-regex', action='store_true', dest='enable_std_regex',
                   default=False,
                   help='turn on using STL\'s regex implementation.  Only works when C++11 support is enabled')

def configure(conf):
    conf.env['enable_std_regex'] = Options.options.enable_std_regex

    def re_callback(conf):
        conf.env['DEFINES'] = []
        if conf.env['enable_std_regex']:
            conf.define('RE_ENABLE_STD_REGEX', 1)

    writeConfig(conf, re_callback, NAME)

def build(bld):
    # We only depend on PCRE if we're not using the STL regex
    modArgs = globals()
    if not bld.env['enable_std_regex']:
        modArgs['USELIB_CHECK'] = 'PCRE'

    bld.module(**modArgs)
