NAME            = 're'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira_1@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'sys'
DEFINES         = 'USE_PCRE'

set_options = configure = distclean = lambda p: None

def build(bld):
    variant = bld.env['VARIANT'] or 'default'
    env = bld.env_of_name(variant)
    
    kw = globals().copy()
    if 'MAKE_PCRE' in env:
        kw['USELIB_LOCAL'] = 'PCRE'
    else:
        kw['USELIB'] = 'PCRE'
    bld.module(**kw)
