NAME            = 'lang'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira_1@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'io re'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
