BLD_DIRS = 'pcre fftw zlib uuid expat sql'

def options(opt):
    opt.sub_options(BLD_DIRS)

def configure(conf):
    conf.sub_config(BLD_DIRS)

def build(bld):
    bld.add_subdirs(BLD_DIRS)

def distclean(ctx):
    ctx.recurse(BLD_DIRS)
