import os
from waflib import Options, Utils
from waflib.TaskGen import feature, before, task_gen
from build import untarFile, handleDefsFile, writeConfig

def options(opt):
    opt.add_option('--enable-lapack', action='store_true',
        dest='enable_lapack', default=False, 
        help='turn on Lapack linkage')
    
def configure(conf):
    driversNode = conf.path
    if Options.options.enable_lapack:
        lapackIncPath = driversNode.abspath()
        lapackLibs = ['lapack','refblas','gfortran']

        conf.check(lib=lapackLibs, uselib_store='LAPACK',
            libpath=lapackIncPath,mandatory=True)
    
def build(bld):
    return 



