from os.path import join, exists
from waflib import Options, Utils
from build import CPPBuildContext

MODULES = 'nitf'

def options(opt):
    opt.recurse(MODULES)

def configure(conf):
    if conf.env['COMPILER_CXX'] == 'msvc':
        conf.env.CXXFLAGS += ['/std:c++latest']
    else:
        conf.env.CXXFLAGS += ['-std=c++2a]
    conf.recurse(MODULES)

def build(bld):
    bld.recurse(MODULES)

def distclean(context):
    context.recurse(MODULES)
