NAME            = 'unique'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira_1@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'except'

set_options = configure = distclean = lambda p: None

def build(bld):
    env = bld.variantEnv
    
    kw = globals().copy()
    if 'MAKE_UUID' in env:
        kw['USELIB_LOCAL'] = 'UUID'
        kw['USELIB'] = 'RPC'
    else:
        kw['USELIB'] = 'UUID RPC'
    bld.module(**kw)
