NAME            = 'unique'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira1@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'except'

set_options = configure = distclean = lambda p: None

def build(bld):
    variant = bld.env['VARIANT'] or 'default'
    env = bld.env_of_name(variant)
    
    kw = globals().copy()
    if 'MAKE_UUID' in env:
        kw['USELIB_LOCAL'] = 'UUID'
        kw['USELIB'] = 'RPC'
    else:
        kw['USELIB'] = 'UUID RPC'
    bld.module(**kw)
