name: Build, unittest

on:
  push:
  schedule:
    # Runs at 09:00 UTC every Saturday
    - cron: '0 9 * * 6'
  workflow_dispatch: # Optional: allows manual triggering for testing


jobs:
  build-cmake-windows:
    strategy:
      matrix:
        os: [windows-latest]
        platform: [x64]
        configuration: [Release]
    name: ${{ matrix.os }}-CMake
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout
    - name: Set up Python
      uses: actions/setup-python@v5 # https://github.com/marketplace/actions/setup-python
      with:
        python-version: '3.7'
    - name: configure
      run: |
        mkdir out
        cd out
        cmake .. -DCMAKE_INSTALL_PREFIX=install\${{ matrix.platform }}-${{ matrix.configuration }} -DPYTHON_VERSION="3.7"
    - name: make
      run: |
        cd out
        # uncomment end of following line for *VERBOSE* output
        cmake --build . --config ${{ matrix.configuration }} -j # -- /verbosity:detailed
        cmake --build . --config ${{ matrix.configuration }} --target install
    - name: test
      run: |
        cd out
        ctest -C ${{ matrix.configuration }} --output-on-failure
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2 # https://github.com/marketplace/actions/setup-msbuild
      with:
        msbuild-architecture: x64
    - name: msbuild
      run: |
        msbuild nitro.sln /p:configuration=${{ matrix.configuration }}


  build-linux-cmake:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: ${{ matrix.os }}-CMake
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout
    - name: Set up Python
      uses: actions/setup-python@v5 # https://github.com/marketplace/actions/setup-python
      with:
        python-version: '3.9'
    - name: configure
      run: |
        mkdir target-Release
        cd target-Release
        cmake .. -DCMAKE_INSTALL_PREFIX=install${{ matrix.os }}CMake-Github -DPYTHON_VERSION=3.9
    - name: make
      run: |
        cd target-Release
        # using the default number of threads (-j) causes G++ to crash
        cmake --build . -j 6
        cmake --build . --target install
    - name: test
      run: |
        cd target-Release
        ctest --output-on-failure
